dist: trusty
sudo: required

language: cpp

matrix:
  include:
    # gcc5
    - os: linux
      env: COMPILER=gcc5 CONFIG=Debug PLATFORM=x86 PACKAGES="g++-5 g++-5-multilib g++-multilib"
    - os: linux
      env: COMPILER=gcc5 CONFIG=Debug PLATFORM=x64 PACKAGES="g++-5"
    - os: linux
      env: COMPILER=gcc5 CONFIG=Release PLATFORM=x86 PACKAGES="g++-5 g++-5-multilib g++-multilib"
    - os: linux
      env: COMPILER=gcc5 CONFIG=Release PLATFORM=x64 PACKAGES="g++-5"

    # clang4
    - os: linux
      env: COMPILER=clang4 CONFIG=Debug PLATFORM=x86 PACKAGES="clang-4.0 libstdc++-5-dev libc6-dev-i386 g++-5-multilib g++-multilib"
    - os: linux
      env: COMPILER=clang4 CONFIG=Debug PLATFORM=x64 PACKAGES="clang-4.0 libstdc++-5-dev"
    - os: linux
      env: COMPILER=clang4 CONFIG=Release PLATFORM=x86 PACKAGES="clang-4.0 libstdc++-5-dev libc6-dev-i386 g++-5-multilib g++-multilib"
    - os: linux
      env: COMPILER=clang4 CONFIG=Release PLATFORM=x64 PACKAGES="clang-4.0 libstdc++-5-dev"

    # clang5
    - os: linux
      env: COMPILER=clang5 CONFIG=Debug PLATFORM=x86 PACKAGES="clang-5.0 libstdc++-5-dev libc6-dev-i386 g++-5-multilib g++-multilib"
    - os: linux
      env: COMPILER=clang5 CONFIG=Debug PLATFORM=x64 PACKAGES="clang-5.0 libstdc++-5-dev"
    - os: linux
      env: COMPILER=clang5 CONFIG=Release PLATFORM=x86 PACKAGES="clang-5.0 libstdc++-5-dev libc6-dev-i386 g++-5-multilib g++-multilib"
    - os: linux
      env: COMPILER=clang5 CONFIG=Release PLATFORM=x64 PACKAGES="clang-5.0 libstdc++-5-dev"

before_install:
    - if [ "$COMPILER" = "clang4" ]; then curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | sudo -E apt-key add -; fi
    - if [ "$COMPILER" = "clang4" ]; then echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" | sudo tee -a /etc/apt/sources.list > /dev/null; fi
    - if [ "$COMPILER" = "clang5" ]; then curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | sudo -E apt-key add -; fi
    - if [ "$COMPILER" = "clang5" ]; then echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main" | sudo tee -a /etc/apt/sources.list > /dev/null; fi
    - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - sudo -E apt-get -yq update
    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install ${PACKAGES}

script:
    - python3 make.py -build -test -${COMPILER} -${CONFIG} -${PLATFORM}
