version: 0.7.0.{build}

environment:
  PYTHON: "C:\\Python33-x64"

image:
- Visual Studio 2015
- Visual Studio 2017

build_script:
- cmd: >-
    IF "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (SET COMPILER=vs2015) ELSE (SET COMPILER=vs2017)

    %PYTHON%\\python.exe make.py -clean -build -unit_test -%COMPILER% -Debug -x86

    %PYTHON%\\python.exe make.py -clean -build -unit_test -%COMPILER% -Release -x86

    %PYTHON%\\python.exe make.py -clean -build -unit_test -%COMPILER% -Debug -x64

    %PYTHON%\\python.exe make.py -clean -build -unit_test -%COMPILER% -Release -x64
