version: 0.5.{build}

environment:
  PYTHON: "C:\\Python33-x64"

image:
- Visual Studio 2015
- Visual Studio 2017

configuration:
- Debug
- Release

build_script:
- cmd: >-
    %PYTHON%\\python.exe make.py -build -%configuration%

test_script:
- cmd: >-
    %PYTHON%\\python.exe make.py -test -%configuration%
